### ISSUE TITLE
Can't launch any games because of special characters in directories

### ISSUE THREAD

**Issue by icup321** [sewer56lol/Reloaded-Mod-Loader#8]
I'm having an issue using this to launch any game with mods and I think it's because my username has special characters in it. When I launch it, the program fails and gives me this error:
![cvb](https://user-images.githubusercontent.com/28464642/42242889-74b181e4-7edd-11e8-8ed6-6a8448e4c4e7.png)
Basically, it's the same issue as this: https://github.com/PCSX2/pcsx2/issues/2478

**Comment by sewer56lol** [comment]
Found the issue, will look into solutions fairly soon.
Should be an easy fix with perhaps a tiny bit of research - as with how I designed Reloaded's source code.

**Comment by sewer56lol** [comment]
Should be fixed as of commits d360fe1527f234dd45e9eb2d06985483db7db5e7 b691cc335cbfe160478079ce2dbd1e5f46bac1f0 e451c0d3920513090c2cbd4bff18691ac680bcd1

Tested with the username, and user directory 【﻿Ａｒｉａｎｒｈｏｄ】（ヷーこ）, both games running from the user directory and from Program Files.
