### ISSUE TITLE
False flag for Windows Defender

### ISSUE THREAD

**Issue by savePinball** [sewer56lol/Reloaded-Mod-Loader#9]
Hopefully this is the correct place to talk about this.
There seems to be a false flag done by Windows Defender about the .exe and other files.

https://www.virustotal.com/#/file/fe44b8dfaef38f18d661bcbc1e824a711dbbc60b57798f6d16ee6645e0b4441a/detection

https://imgur.com/JHnsNMN

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fZpevdo.A&threatid=2147727143

P.S Found out about this from the PCGaming Wiki article on Sonic Heroes so keep up the good work!

**Comment by sewer56lol** [comment]
This is the most correct place there would be to talk about this, good job 👍 

Sorry for that - it happens all the time :/. It's not very fun sending false positive reports to all of the different antivirus vendors by hand every time someone reports one of those.

The funny thing is that this is actually a second for Windows Defender, 7 weeks ago I had to make the exact same report - for the same executable, a couple of versions ago; oof!

PS. Have fun playing Sonic Heroes ^-^

**Comment by sewer56lol** [comment]
Oh, oof, I just got that too; literally minutes after.

The interesting thing is the file that was detected, is actually just a proxy/renamed version of a component of the library I use for software updates: https://github.com/Squirrel/Squirrel.Windows so the false positive was not thrown at my code this time around, but a hugely popular third party open source library.

Oh well; it'll probably be resolved in a few hours after I send the ticket in.

**Comment by sewer56lol** [comment]
Got the automated email back.
Should be fixed after the next update of definitions in WinDefender. 👌
